---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04
    driver:
      box: trusty-server-cloudimg-amd64-vagrant-disk1
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: default
    run_list:
      - recipe[pw_dnsmasq::default]
    attributes:
      pw_dnsmasq:
        interface: 'eth0'
        gw_ip: '10.0.2.15'
        rubygems_mirror_ip: ''
